### ISSUE TITLE
No "IIIF Search URL" in the IIIF Server settings

### ISSUE THREAD

**Issue by smorello87** [symac/Omeka-S-module-IiifSearch#2]
Hi – I tried to follow the installation instructions for IiifSearch, but I was unable to get it to work. The instructions seem to require that I add the following url: http://yourdomain/omeka-s/iiif-search/ to the “IIIF Search Url” field in the IIIF Server’s settings, however, I can’t find such thing in my settings. Any heads up?

![Screen Shot 2019-03-18 at 3 46 07 PM](https://user-images.githubusercontent.com/35434644/54558814-012a1280-4995-11e9-8c6c-85e4c52b8dd8.png)
![Screen Shot 2019-03-18 at 3 46 21 PM](https://user-images.githubusercontent.com/35434644/54558815-01c2a900-4995-11e9-866b-be6d219a51bb.png)

Many thanks!!
-Stefano

**Comment by symac** [comment]
Hi Stefano @smorello87 ,
sorry for the late reply, this omeka-s migration has been long delayed on our side but I am coming back to it. 

The issue was that the IiifServer screenshot shown was one with customization on our side that had not been committed to the main repository of IiifServer. I have just opened a [PR that fixes that](https://github.com/Daniel-KM/Omeka-S-module-IiifServer/pull/16)

**Comment by m-art-in** [comment]
Unfortunately it's not in the master yet.

**Comment by symac** [comment]
@m-art-in it is in master but not in the latest release from what I can see, pinging @Daniel-KM to see if he can do something to fix it.

**Comment by m-art-in** [comment]
You're right, I confused master and release. 
Thank you very much, it worked now.
